//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magenta_S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int Idu { get; set; }
        public int Idproduct { get; set; }
        public int Idbill { get; set; }
        public int Count { get; set; }
        public bool Ok { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
